{{- if .Values.controller.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-controller
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 18300
      protocol: "TCP"
      name: "cluster-tcp-18300"
    - port: 18301
      protocol: "TCP"
      name: "cluster-tcp-18301"
    - port: 18301
      protocol: "UDP"
      name: "cluster-udp-18301"
  selector:
    app: neuvector-controller-pod
{{- end }}
---
{{- if .Values.controller.apisvc.type -}}
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-controller-api
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.controller.apisvc.type }}
  ports:
    - port: 10443
      protocol: "TCP"
      name: "controller-api"
  selector:
    app: neuvector-controller-pod
{{- end -}}
